### ISSUE TITLE
EXIF writing

### ISSUE THREAD

**Issue by lehitoskin** [Kalimehtar/binary-class-exif#1]
In the README description this library is supposed to be able to read and modify EXIF tags, but looking through the source I can't find anything that might be what I want. Have you added that functionality yet?

**Comment by Kalimehtar** [comment]
You may use [write-value](https://docs.racket-lang.org/binary-class/index.html#%28def._%28%28lib._binary-class%2Fbase..rkt%29._write-value%29%29).
So you read-value, change the object with set-field, then call write-value to save changes.

**Comment by lehitoskin** [comment]
Ah, I'm not exactly sure how to do that in practice. I read over some of the documentation, but I didn't really understand anything :P

**Comment by Kalimehtar** [comment]
Would be something like this:
```
(define test (call-with-input-file "yourfile.tiff" read-tiff-file-props))
(define data (get-field current-part (get-field data (get-field first-ifd (get-field tiff-header test)))))
(define item (for/first ([i data] #:when (eq? (get-field tag i) 'tiff:date-time)) i))
(set-field! value item "1998:12:01 14:22:00")
(call-with-output-file "yourfile.tiff" #:exists 'update (lambda (out) (write-value tiff out test)))
```
Don't increase size of the values (it isn't checked, so you may overwrite image with new header, if new value is longer, than the old one).

**Comment by lehitoskin** [comment]
Oh, okay. Thanks for the pointers!
